language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/Gemfile.rails3_2
  - gemfiles/Gemfile.rails4_0
  - gemfiles/Gemfile.rails4_1
  - gemfiles/Gemfile.rails4_2
before_script:
  - cd spec/dummy && bundle exec rake db:test:load && cd -
